### ISSUE TITLE
This is now flagged down by Windows 11 as "containing virus"

### ISSUE THREAD

**Issue by dutchsnowden** [emeric-martineau/wsl-gui-tool#3]
Not sure what is going on but this is now flagged down as containing virus and cannot be executed by default in Windows 11.

**Comment by SHJordan** [comment]
Not here... Can you provide proof and the name of the detected malware?
I'm on 22000.527 update.

> Not sure what is going on but this is now flagged down as containing virus and cannot be executed by default in Windows 11.

**Comment by emeric-martineau** [comment]
Hi,
sorry, I don't have Windows 11 yet. But when I can do some tests, I will be fix if possible.

**Comment by skoro** [comment]
Should be fixed in PR https://github.com/emeric-martineau/wsl-gui-tool/pull/6
